export const dataItems = [
  {
    id: 1,
    category: "food",
    image: require("../../../images/cheeseburgare.jpg"),
    price: 10,
    title: "CheeseBurger",
    amount: 10,
  },
  {
    id: 2,
    category: "food",
    image: require("../../../images/pannkaka-ny.jpg"),
    price: 10,
    title: "Pannkaka",
    amount: 10,
  },
  {
    id: 3,
    category: "food",
    image: require("../../../images/cheeseburgare.jpg"),
    price: 10,
    title: "Kyckling",
    amount: 10,
  },
  {
    id: 4,
    category: "food",
    image: require("../../../images/cheeseburgare.jpg"),
    price: 10,
    title: "Pannkaka",
    amount: 10,
  },
  {
    id: 5,
    category: "food",
    image: require("../../../images/cheeseburgare.jpg"),
    price: 10,
    title: "Pannkaka",
    amount: 10,
  },
  {
    id: 6,
    category: "food",
    image: require("../../../images/cheeseburgare.jpg"),
    price: 10,
    title: "Pannkaka",
    amount: 10,
  },
  {
    id: 7,
    category: "food",
    image: require("../../../images/cheeseburgare.jpg"),
    price: 10,
    title: "Pannkaka",
    amount: 10,
  },
  {
    id: 8,
    category: "food",
    image: require("../../../images/cheeseburgare.jpg"),
    price: 10,
    title: "Pannkaka",
    amount: 10,
  },
  {
    id: 9,
    category: "food",
    image: require("../../../images/cheeseburgare.jpg"),
    price: 10,
    title: "Pannkaka",
    amount: 10,
  },
];
